project:
  type: book

book:
  title: "SD2005 - From Sustaible Development to Human Security"
  subtitle: "Techincal Practices required for the Quantitave Data Report"
  author: "Fernando Benitez-Paez"
  date: "7/3/2025"
  downloads: [pdf]
  sidebar:
    style: "docked"
    background: light
  chapters:
    - index.qmd
    - intro.qmd
    - Lab_1.qmd
    - Lab_2.qmd
    - Lab_3.qmd
    - Lab_4.qmd
    - Lab_5.qmd
    - DataSources.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    respect-user-color-scheme: true
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  freeze: auto

